<a href="https://colab.research.google.com/github/PHCoder05/advance-python-practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Numpy

**What is NumPy?**

- Python library
- stands for Numerical Python.
- used for working with arrays
- linear algebra, fourier transform, and matrices.
- created in 2005 by Travis Oliphant.
- open source

**Why Use NumPy?**

- previously list was used at the place of array
- it is slow
- numpy introduced array Object
- it is 50x faster
- this array object called as ndarray
- used in mostly data science where speed and resoures


**Why is NumPy Faster Than Lists?**

- one continuous place in memory unlike lists
- called locality of reference in computer science
- optimized to work with latest CPU architectures.

**Which Language is NumPy written in?**

- Python
- some in c & c++ for faster computation

**Where is the NumPy Codebase?**

- github repository https://github.com/numpy/numpy

**Installation of NumPy**

In [3]:
pip install numpy

**Checking NumPy Version**

In [2]:
import numpy as np

print(np.__version__)

1.25.2


**Create a NumPy ndarray Object**

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


**Check Number of Dimensions?**

In [1]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


**Higher Dimensional Arrays**

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# NumPy Array Indexing


**Access array Element**

In [7]:
arr = np.array([1, 2, 3, 4])
print(arr[1])

2


**Negative Indexing**

In [8]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# NumPy Array Slicing



In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


**Negative Slicing**

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


# Steps
**Use the step value to determine the step of the slicing:**


In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])


[2 4]


Numpy Empty Function

In [14]:
# prompt: data types using numpy

# NumPy Data Types
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

# For i, u, f, S and U we can define size as well.
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)


[[4.93811076e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]
