<a href="https://colab.research.google.com/github/PHCoder05/advance-python-practice/blob/main/Numpy_80_fucntions_with_descriptions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Numpy

**What is NumPy?**

- Python library
- stands for Numerical Python.
- used for working with arrays
- linear algebra, fourier transform, and matrices.
- created in 2005 by Travis Oliphant.
- open source

**Why Use NumPy?**

- previously list was used at the place of array
- it is slow
- numpy introduced array Object
- it is 50x faster
- this array object called as ndarray
- used in mostly data science where speed and resoures


**Why is NumPy Faster Than Lists?**

- one continuous place in memory unlike lists
- called locality of reference in computer science
- optimized to work with latest CPU architectures.

**Which Language is NumPy written in?**

- Python
- some in c & c++ for faster computation

**Where is the NumPy Codebase?**

- github repository https://github.com/numpy/numpy

**Installation of NumPy**

In [ ]:
pip install numpy

**Checking NumPy Version**

In [ ]:
import numpy as np

print(np.__version__)

1.25.2


**Create a NumPy ndarray Object**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


**Check Number of Dimensions?**

In [ ]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


**Higher Dimensional Arrays**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# NumPy Array Indexing


**Access array Element**

In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr[1])

2


**Negative Indexing**

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# NumPy Array Slicing



In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


**Negative Slicing**

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


# Steps
**Use the step value to determine the step of the slicing:**


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])


[2 4]


Numpy Empty Function

In [ ]:
# prompt: data types using numpy

# NumPy Data Types
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

# For i, u, f, S and U we can define size as well.
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)


[[4.93811076e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]


**The np.arange() function is used to create arrays with regularly spaced values within a specified range.**

In [1]:
import numpy as np
array = np.arange(5)
print(array)


[0 1 2 3 4]


**The np.zeros() function is part of the NumPy library and is used to create a new array filled with zeros.**

In [2]:
import numpy as np
array = np.zeros(5)
print(array)


[0. 0. 0. 0. 0.]


**The np.ones() function returns a numpy.ndarray with the specified shape and data type, where all elements are initialized to one.**

In [3]:
import numpy as np
array = np.ones(5)
print(array)


[1. 1. 1. 1. 1.]


**The np.empty() function in NumPy is used to create a new array with uninitialized values.**

In [4]:
import numpy as np
array = np.empty(5)
print(array)


[0. 0. 0. 0. 0.]


**The fill() method is used to set all elements of the array to a specified value. This method modifies the array in-place, meaning that it changes the array directly without creating a new one.**


In [5]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
array.fill(0)
print(array)


[0 0 0 0 0]


**The np.linspace() function is used to generate linearly spaced values between a specified start and stop value.**

In [6]:
import numpy as np
array = np.linspace(0, 1, num=5)
print(array)


[0.   0.25 0.5  0.75 1.  ]


**The np.logspace() function in NumPy generates numbers spaced evenly on a log scale.**

In [7]:
import numpy as np
array = np.logspace(0, 1, num=5)
print(array)


[ 1.          1.77827941  3.16227766  5.62341325 10.        ]


#Aggregate Functions

**1. np.min()**

Computes the minimum value of an array.

In [8]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
print(np.min(array))


1


**2. np.max()**

Computes the maximum value of an array.



In [9]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
print(np.max(array))


6


**3. np.sum()**

Computes the sum of array elements.

In [10]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(array))


21


**4. np.mean()**

Computes the arithmetic mean of array elements.

In [11]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
print(np.mean(array))


3.5


**5. np.median()**

Computes the median of array elements.

In [12]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
print(np.median(array))


3.5


**6. np.std()**

Computes the standard deviation of array elements.

In [13]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
print(np.std(array))


1.707825127659933


**7. np.var()**

Computes the variance of array elements.

In [14]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
print(np.var(array))


2.9166666666666665


#Numpy other Functions

**np.random.random()**


Generates random numbers from a uniform distribution over [0, 1). This means that the generated numbers will be between 0 (inclusive) and 1 (exclusive.

In [16]:
import numpy as np

random_number = np.random.random()
print(random_number)


0.9953520015327874


**The np.stack() function in NumPy is used to join a sequence of arrays along a new axis. This is particularly useful for combining multiple arrays of the same shape into a single multidimensional array.**

In [17]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

result = np.stack((a, b, c), axis=0)
print(result)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


**The np.split() function returns a list of sub-arrays obtained by splitting the input array.**

In [18]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])
result = np.split(array, 3)
print(result)


[array([1, 2]), array([3, 4]), array([5, 6])]


**The np.sort() function in NumPy is used to sort an array along a specified axis. It returns a sorted copy of the array, leaving the original array unchanged.**

In [19]:
import numpy as np

array = np.array([3, 1, 2, 5, 4])
sorted_array = np.sort(array)
print(sorted_array)


[1 2 3 4 5]
